<!DOCTYPE html>
<html>
<body>
<h2>Symfony Github Repositories -</h2>
<?php
	// This autoload file is generated by Composer
	require_once 'vendor/autoload.php';
	//create objects of githhub client class 
	$client = new \Github\Client();
	//client api method to call Symfony repos
	$repositories = $repos = $client->api('repo')->find('symfony',array('language' => 'php'));
	//$client->api('user')->repositories('symfony');

	foreach($repositories['repositories'] as $key=>$repo) {
		echo "<ul><li>". $repo['name']."</li></ul>";
	}
?>

</body>
</html>